export const streetsAndPeacksQuiz = [
  {
    id: 'level1',
    title: 'City Streets',
    questions: [
      {
        id: '1',
        image: require('../../assets/images/streetsnpeacksim1.png'),
        text: 'Which street is known as one of the oldest in Montreal?',
        options: [
          'Rue Saint-Paul',
          'Boulevard René-Lévesque',
          'Avenue du Parc',
        ],
        correctIndex: 0,
      },
      {
        id: '2',
        image: require('../../assets/images/streetsnpeacksim2.png'),
        text: 'This street is famous for its shopping and nightlife.',
        options: [
          'Rue Sherbrooke',
          'Rue Sainte-Catherine',
          'Avenue Mont-Royal',
        ],
        correctIndex: 1,
      },
      {
        id: '3',
        image: require('../../assets/images/streetsnpeacksim3.png'),
        text: 'Known as “The Main,” it divides east and west Montreal.',
        options: ['Boulevard Saint-Laurent', 'Rue Crescent', 'Avenue du Musée'],
        correctIndex: 0,
      },
      {
        id: '4',
        image: require('../../assets/images/streetsnpeacksim4.png'),
        text: 'A vibrant street known for cafes, boutiques, and murals.',
        options: ['Avenue du Mont-Royal', 'Rue Notre-Dame', 'Rue Peel'],
        correctIndex: 0,
      },
      {
        id: '5',
        image: require('../../assets/images/streetsnpeacksim5.png'),
        text: 'Home to museums and universities, this street stretches across the island.',
        options: [
          'Rue Saint-Paul',
          'Rue Sherbrooke',
          'Boulevard De Maisonneuve',
        ],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'level2',
    title: 'Parks & Peaks',
    questions: [
      {
        id: '1',
        image: require('../../assets/images/streetsnpeacksim6.png'),
        text: 'Which park gives you the best panoramic view of Montreal?',
        options: ['Parc La Fontaine', 'Mount Royal Park', 'Parc Jean-Drapeau'],
        correctIndex: 1,
      },
      {
        id: '2',
        image: require('../../assets/images/streetsnpeacksim7.png'),
        text: 'This park hosted Expo 67.',
        options: ['Parc Maisonneuve', 'Parc Jean-Drapeau', 'Westmount Park'],
        correctIndex: 1,
      },
      {
        id: '3',
        image: require('../../assets/images/streetsnpeacksim8.png'),
        text: 'A popular park in the Plateau area known for its ponds.',
        options: ['Parc La Fontaine', 'Mount Royal Park', 'Jarry Park'],
        correctIndex: 0,
      },
      {
        id: '4',
        image: require('../../assets/images/streetsnpeacksim9.png'),
        text: 'From here, you can see all of downtown Montreal.',
        options: ['Mount Royal Belvedere', 'Beaver Lake', 'Parc Angrignon'],
        correctIndex: 0,
      },
      {
        id: '5',
        image: require('../../assets/images/streetsnpeacksim10.png'),
        text: 'Located near the Botanical Garden, perfect for picnics.',
        options: ['Parc Maisonneuve', 'Jarry Park', 'Parc La Fontaine'],
        correctIndex: 0,
      },
    ],
  },
  {
    id: 'level3',
    title: 'Famous Buildings',
    questions: [
      {
        id: '1',
        image: require('../../assets/images/streetsnpeacksim11.png'),
        text: 'Which iconic building was designed for Expo 67?',
        options: ['Habitat 67', 'Montreal Tower', 'Palais des congrès'],
        correctIndex: 0,
      },
      {
        id: '2',
        image: require('../../assets/images/streetsnpeacksim12.png'),
        text: 'This Gothic Revival church is one of the city’s top landmarks.',
        options: [
          'St. Joseph’s Oratory',
          'Notre-Dame Basilica',
          'Christ Church Cathedral',
        ],
        correctIndex: 1,
      },
      {
        image: require('../../assets/images/streetsnpeacksim13.png'),
        text: 'Home of the 1976 Olympic Games.',
        options: ['Olympic Stadium', 'Bell Centre', 'Windsor Station'],
        correctIndex: 0,
      },
      {
        id: '4',
        image: require('../../assets/images/streetsnpeacksim14.png'),
        text: 'Canada’s largest church, located on Mount Royal.',
        options: [
          'St. Joseph’s Oratory',
          'Notre-Dame Basilica',
          'Christ Church Cathedral',
        ],
        correctIndex: 0,
      },
      {
        id: '5',
        image: require('../../assets/images/streetsnpeacksim15.png'),
        text: 'Historic building from the 19th century in Old Montreal.',
        options: [
          'Montreal City Hall',
          'Place Ville Marie',
          'Sun Life Building',
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: 'level4',
    title: 'Cultural Montreal',
    questions: [
      {
        id: '1',
        image: require('../../assets/images/streetsnpeacksim16.png'),
        text: 'Where can you find major art performances and symphonies?',
        options: ['Place des Arts', 'Musée McCord', 'Centre Phi'],
        correctIndex: 0,
      },
      {
        id: '2',
        image: require('../../assets/images/streetsnpeacksim17.png'),
        text: 'This is the largest museum in the city.',
        options: [
          'Montreal Museum of Fine Arts',
          'Redpath Museum',
          'Musée d’art contemporain',
        ],
        correctIndex: 0,
      },
      {
        id: '3',
        image: require('../../assets/images/streetsnpeacksim18.png'),
        text: 'Which neighborhood is known for street art and cafes?',
        options: ['Le Plateau', 'Old Port', 'Mile-End'],
        correctIndex: 0,
      },
      {
        id: '4',
        image: require('../../assets/images/streetsnpeacksim19.png'),
        text: 'Montreal’s entertainment district, full of festivals.',
        options: ['Quartier des Spectacles', 'Chinatown', 'Saint-Henri'],
        correctIndex: 0,
      },
      {
        id: '5',
        image: require('../../assets/images/streetsnpeacksim20.png'),
        text: 'Home of the Orchestre Symphonique de Montréal.',
        options: [
          'Montreal Symphony House',
          'Place Bonaventure',
          'Théâtre Saint-Denis',
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: 'level5',
    title: 'Historic & Old Port',
    questions: [
      {
        id: '1',
        image: require('../../assets/images/streetsnpeacksim21.png'),
        text: 'What’s the waterfront area famous for its festivals?',
        options: ['Old Port of Montreal', 'Chinatown', 'Downtown Core'],
        correctIndex: 0,
      },
      {
        id: '2',
        image: require('../../assets/images/streetsnpeacksim22.png'),
        text: 'Historic market building from the 19th century.',
        options: ['Bonsecours Market', 'Atwater Market', 'Jean-Talon Market'],
        correctIndex: 0,
      },
      {
        id: '3',
        image: require('../../assets/images/streetsnpeacksim23.png'),
        text: 'Popular square in Old Montreal filled with artists and cafes.',
        options: [
          'Place Jacques-Cartier',
          'Place Ville Marie',
          'Dorchester Square',
        ],
        correctIndex: 0,
      },
      {
        id: '4',
        image: require('../../assets/images/streetsnpeacksim24.png'),
        text: 'Archaeology and history museum built on Montreal’s birthplace.',
        options: [
          'Pointe-à-Callière Museum',
          'McCord Museum',
          'Stewart Museum',
        ],
        correctIndex: 0,
      },
      {
        id: '5',
        image: require('../../assets/images/streetsnpeacksim25.png'),
        text: 'Historic tower offering a view of the St. Lawrence River.',
        options: ['Clock Tower', 'Montreal Tower', 'Victoria Tower'],
        correctIndex: 0,
      },
    ],
  },
  {
    id: 'level6',
    title: 'Bonus: Local Trivia',
    questions: [
      {
        id: '1',
        text: 'Montreal’s metro trains run on…',
        options: ['Rubber tires', 'Metal wheels'],
        image: require('../../assets/images/streetsnpeacksimbon.png'),
        correctIndex: 0,
      },
      {
        id: '2',
        text: 'What language is most commonly spoken in Montreal?',
        image: require('../../assets/images/streetsnpeacksimbon.png'),
        options: ['French', 'English'],
        correctIndex: 0,
      },
      {
        id: '3',
        text: 'Which festival celebrates comedy every summer?',
        image: require('../../assets/images/streetsnpeacksimbon.png'),
        options: ['Just for Laughs', 'Jazz Fest'],
        correctIndex: 0,
      },
      {
        id: '4',
        text: 'What’s the name of Montreal’s famous winter festival?',
        image: require('../../assets/images/streetsnpeacksimbon.png'),
        options: ['Igloofest', 'Lumière Fest'],
        correctIndex: 0,
      },
      {
        id: '5',
        text: 'Which type of food is Montreal especially known for?',
        image: require('../../assets/images/streetsnpeacksimbon.png'),
        options: ['Bagels', 'Tacos'],
        correctIndex: 0,
      },
      {
        id: '6',
        text: 'The island of Montreal is surrounded by…',
        options: ['The St. Lawrence River', 'The Ottawa River'],
        image: require('../../assets/images/streetsnpeacksimbon.png'),
        correctIndex: 0,
      },
      {
        id: '7',
        text: 'What color are Montreal’s metro line indicators?',
        options: ['Blue, Green, Orange, Yellow', 'Red, Pink, Purple, Black'],
        image: require('../../assets/images/streetsnpeacksimbon.png'),
        correctIndex: 0,
      },
      {
        id: '8',
        text: 'What’s the main mode of winter transport for many locals?',
        image: require('../../assets/images/streetsnpeacksimbon.png'),
        options: ['Metro and walking', 'Boats and bicycles'],
        correctIndex: 0,
      },
    ],
  },
];
